-- MMSM E2 验证脚本(自动生成,需在 DM8 环境执行)
-- 语句数:37;生成日期:2026-09-06
-- 注意:仅验证语法可执行性(SELECT 返回列/类型),不验证结果等价性
-- 期望结果:全部语句编译通过,SELECT 语句返回结果集

-- [CHANGE-339] libMMSM/f_mmsm81.cpp L101
SELECT MMSM_MATNO_SEQ.NEXTVAL FROM DUAL;

-- [CHANGE-151] libMMSM/f_mmsm7101_proc.cpp L84-L84
SELECT MAX(SUBSTR(SLAG_PROC_NO, 5, 5)) + 1 FROM TMMSM71 WHERE SUBSTR(SLAG_PROC_NO, 1, 2) = (SELECT substr(to_char(CURRENT_DATE,'yyyy'),3,2) FROM DUAL);

-- [CHANGE-152] libMMSM/f_mmsm7101_proc.cpp L98-L98
SELECT MAX(SUBSTR(SLAG_PROC_NO, 5, 5)) + 1 FROM TMMSM71 WHERE SUBSTR(SLAG_PROC_NO, 1, 2) = (SELECT substr(to_char(CURRENT_DATE,'yyyy'),3,2) FROM DUAL);

-- [CHANGE-153] libMMSM/f_mmsm80a.cpp L447-L449
SELECT TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISSFF4') FROM DUAL;

-- [CHANGE-154] libMMSM/f_mmsm_acyfl_seq.cpp L44-L47
SELECT LPAD(TO_CHAR(MMSM_MATNO_SEQ.NEXTVAL),4,'0') FROM DUAL;

-- [CHANGE-155] libMMSM/f_mmsm_get_density.cpp L58-L58
select CODE_DESC_1_CONTENT,CASE WHEN trim(CODE_DESC_2_CONTENT) IS NULL OR trim(CODE_DESC_2_CONTENT) = '' THEN 7.85 ELSE trim(CODE_DESC_2_CONTENT) END CODE_DESC_2_CONTENT from TWMSMZD02 where CODE_CLASS='MMSMDENS' ORDER BY CODE;

-- [CHANGE-156] libMMSM/f_mmsm_get_seq_no.cpp L68-L70
SELECT LPAD(TO_CHAR(MMSM_MATNO_SEQ.NEXTVAL),6,'0') FROM DUAL;

-- [CHANGE-157] libMMSM/f_mmsm_get_seq_no.cpp L156-L158
SELECT LPAD(TO_CHAR(MMSM_MATNO_SEQ.NEXTVAL),6,'0') FROM DUAL;

-- [CHANGE-158] libMMSM/f_mmsm_gyupd.cpp L148-L158
-- 以下为写操作,执行前确认在测试环境!
insert into tmmsmgy08(REC_CREATOR,REC_CREATE_TIME,sm_plan_nol2,heat_no,l2_proc_no,PROC_NO,dev_code,mat_code,DEVO_TIME,DEVO_WT,HANDLE_DIV) select '测试值','测试值',t1.sm_plan_nol2,t1.heat_no,t1.l2_proc_no,t1.PROC_NO,t1.dev_code,'TS0000',t1.START_TIME,case when nvl((select DES_TREATMENT_NO from tmmsm21 t2 where t2.heat_no= t1.l2_proc_no and rownum=1),' ')=' ' then round(MOLTIRON_WT*RATIO_B* CASE WHEN BACK_C1 > 0 THEN (BACK_C1*0.01) ELSE 1 / HEAT_COUNT END*1000,0) else round(MOLTIRON_WT*RATIO_B*RATIO_KR* CASE WHEN BACK_C1 > 0 THEN (BACK_C1*0.01) ELSE 1 / HEAT_COUNT END*1000,0) end,HANDLE_DIV from ( select sm_plan_nol2,heat_no,l2_proc_no,PROC_NO,dev_code,decode(HEAT_COUNT,0,1,HEAT_COUNT) HEAT_COUNT,TO_NUMBER(TRIM(CASE WHEN trim(BACK_C1) IS NULL THEN 0 ELSE BACK_C1 END)) as BACK_C1,HANDLE_DIV,START_TIME,RATIO_B,RATIO_KR from tmmsmgy06 t1 ,tmmsmw3 t3 where 1=1 and dev_code like 'B%' and heat_no='测试值' ) t1 left join tmmsmgy05 t2 on t1.l2_proc_no=t2.heat_no where nvl(MOLTIRON_WT,0)!=0;

-- [CHANGE-159] libMMSM/f_mmsm_gyupd.cpp L184-L195
-- 以下为写操作,执行前确认在测试环境!
insert into tmmsmgy08(REC_CREATOR,REC_CREATE_TIME,sm_plan_nol2,heat_no,l2_proc_no,PROC_NO,dev_code,mat_code,DEVO_TIME,DEVO_WT,HANDLE_DIV) select '测试值','测试值',t1.sm_plan_nol2,t1.heat_no,t1.l2_proc_no,t1.PROC_NO,t1.dev_code,'TS0000',t1.START_TIME,case when nvl((select DES_TREATMENT_NO from tmmsm21 t2 where t2.heat_no= t1.l2_proc_no and rownum=1),' ')=' ' then round(MOLTIRON_WT*RATIO_B* CASE WHEN BACK_C1 > 0 THEN (BACK_C1*0.01) ELSE 1 / HEAT_COUNT END*1000,0) else round(MOLTIRON_WT*RATIO_B*RATIO_KR* CASE WHEN BACK_C1 > 0 THEN (BACK_C1*0.01) ELSE 1 / HEAT_COUNT END*1000,0) end,HANDLE_DIV from ( select sm_plan_nol2,heat_no,l2_proc_no,PROC_NO,dev_code,decode(HEAT_COUNT,0,1,HEAT_COUNT) HEAT_COUNT,TO_NUMBER(TRIM(CASE WHEN trim(BACK_C1) IS NULL THEN 0 ELSE BACK_C1 END)) as BACK_C1,HANDLE_DIV,START_TIME,RATIO_B,RATIO_KR from tmmsmgy06 t1 ,tmmsmw3 t3 where 1=1 and not exists(select 1 from tmmsmgy05 t4 WHERE t1.l2_proc_no = t4.heat_no) and dev_code like 'B%' and heat_no='测试值' ) t1 left join tmmsm21 t2 on t1.l2_proc_no=t2.l2_proc_no where nvl(MOLTIRON_WT,0)!=0;

-- [CHANGE-160] libMMSM/f_mmsm_gyupd.cpp L244-L255
-- 以下为写操作,执行前确认在测试环境!
insert into tmmsmgy08(REC_CREATOR,REC_CREATE_TIME,sm_plan_nol2,heat_no,l2_proc_no,PROC_NO,dev_code,mat_code,ID_2A,PROC_COUNT,WEIGH_NO,QUALITY_BATCH_NO,LOT_NO,DEVO_TIME,DEVO_WT,HANDLE_DIV,STK_NO,CHARGE_TYPE) select '测试值','测试值',sm_plan_nol2,heat_no,l2_proc_no,PROC_NO,dev_code,mat_code,ID_2A,PROC_COUNT,WEIGH_NO,QUALITY_BATCH_NO,LOT_NO,DEVO_TIME,round(sum(DEVO_WT* CASE WHEN BACK_C1 > 0 THEN (BACK_C1*0.01) ELSE 1 / HEAT_COUNT END),0) DEVO_WT,NVL(trim(HANDLE_DIV),'I'),STK_NO,CHARGE_TYPE from ( select t1.sm_plan_nol2,t1.heat_no,t1.l2_proc_no,t1.proc_no,t1.dev_code,decode(t1.HEAT_COUNT,0,1,t1.HEAT_COUNT) HEAT_COUNT,TO_NUMBER(TRIM(CASE WHEN trim(BACK_C1) IS NULL THEN 0 ELSE BACK_C1 END)) as BACK_C1,t2.mat_code,t2.ID_2A,t2.PROC_COUNT,t2.WEIGH_NO,t2.LOT_NO,t2.QUALITY_BATCH_NO,t2.DEVO_TIME,t2.DEVO_WT,t1.HANDLE_DIV,t2.STK_NO,t2.CHARGE_TYPE from tmmsmgy06 t1 left join tmmsm2a_yl t2 on t1.dev_code = t2.dev_code and t1.l2_proc_no=t2.l2_proc_no where 1=1 and substr(t1.dev_code,1,1) not in ('F','R','S','V') and nvl(DEVO_WT,0)!=0 and t1.heat_no= '测试值') group by sm_plan_nol2,heat_no,l2_proc_no,PROC_NO,dev_code,mat_code,ID_2A,PROC_COUNT,WEIGH_NO,QUALITY_BATCH_NO,LOT_NO,DEVO_TIME,STK_NO,CHARGE_TYPE,NVL(trim(HANDLE_DIV),'I');

-- [CHANGE-161] libMMSM/f_mmsm_gyupd.cpp L281-L292
-- 以下为写操作,执行前确认在测试环境!
insert into tmmsmgy08(REC_CREATOR,REC_CREATE_TIME,sm_plan_nol2,heat_no,l2_proc_no,PROC_NO,dev_code,mat_code,ID_2A,PROC_COUNT,WEIGH_NO,QUALITY_BATCH_NO,LOT_NO,DEVO_TIME,DEVO_WT,HANDLE_DIV,STK_NO,CHARGE_TYPE) select '测试值','测试值',sm_plan_nol2,heat_no,l2_proc_no,PROC_NO,dev_code,mat_code,ID_2A,PROC_COUNT,WEIGH_NO,QUALITY_BATCH_NO,LOT_NO,DEVO_TIME,round(sum(DEVO_WT* CASE WHEN BACK_C1 > 0 THEN (BACK_C1*0.01) ELSE 1 / HEAT_COUNT END),0) DEVO_WT,NVL(trim(HANDLE_DIV),'I'),STK_NO,CHARGE_TYPE from ( select t1.sm_plan_nol2,t1.heat_no,t1.l2_proc_no,t1.proc_no,t1.dev_code,decode(t1.HEAT_COUNT,0,1,t1.HEAT_COUNT) HEAT_COUNT,TO_NUMBER(TRIM(CASE WHEN trim(BACK_C1) IS NULL THEN 0 ELSE BACK_C1 END)) as BACK_C1,t2.mat_code,t2.ID_2A,t2.PROC_COUNT,t2.WEIGH_NO,t2.QUALITY_BATCH_NO,t2.LOT_NO,t2.DEVO_TIME,t2.DEVO_WT,t1.HANDLE_DIV,t2.STK_NO,t2.CHARGE_TYPE from tmmsmgy06 t1 left join tmmsm2a_yl t2 on substr(t1.dev_code,1,1) = substr(t2.dev_code,1,1) and t1.l2_proc_no=t2.l2_proc_no where 1=1 and substr(t1.dev_code,1,1) in ('F','R','S','V') and nvl(DEVO_WT,0)!=0 and t1.heat_no= '测试值') group by sm_plan_nol2,heat_no,l2_proc_no,PROC_NO,dev_code,mat_code,ID_2A,PROC_COUNT,WEIGH_NO,QUALITY_BATCH_NO,LOT_NO,DEVO_TIME,STK_NO,CHARGE_TYPE,NVL(trim(HANDLE_DIV),'I');

-- [CHANGE-162] libMMSM/f_mmsm_matno_catch_sm.cpp L597-L597
SELECT chr(to_number(ABS(ASCII('测试值') - 55))+55+1) FROM DUAL;

-- [CHANGE-362] p_mmsm_17520/mmsm01g2_inq.cpp L135-L136
OR ( A.WHOLE_BACKLOG LIKE '测试值' AND (INSTR(A.WHOLE_BACKLOG, '测试值')-INSTR(A.WHOLE_BACKLOG, '测试值')/2 *2)>0);

-- [CHANGE-363] p_mmsm_17520/mmsm01g2_inq.cpp L147-L148
OR ( A.WHOLE_BACKLOG LIKE '测试值' AND (INSTR(A.WHOLE_BACKLOG, '测试值')-INSTR(A.WHOLE_BACKLOG, '测试值')/2 *2)>0);

-- [CHANGE-364] p_mmsm_17520/mmsm01g2_inq.cpp L160-L161
OR ( A.WHOLE_BACKLOG LIKE '测试值' AND (INSTR(A.WHOLE_BACKLOG, '测试值')-INSTR(A.WHOLE_BACKLOG, '测试值')/2 *2)>0);

-- [CHANGE-365] p_mmsm_17520/mmsmis02a1_inq.cpp L312-L313
AND ((a.WHOLE_BACKLOG like '测试值' and (INSTR(a.WHOLE_BACKLOG, '测试值') - INSTR(a.WHOLE_BACKLOG, '测试值')/2 *2) > 0 );

-- [CHANGE-366] p_mmsm_17520/mmsmis02a1_inq.cpp L327-L328
OR (a.WHOLE_BACKLOG like '测试值' and (INSTR(a.WHOLE_BACKLOG, '测试值') - INSTR(a.WHOLE_BACKLOG, '测试值')/2 *2) > 0 );

-- [CHANGE-367] p_mmsm_17520/mmsmis02a1_inq.cpp L342-L343
OR (a.WHOLE_BACKLOG like '测试值' and (INSTR(a.WHOLE_BACKLOG, '测试值') - INSTR(a.WHOLE_BACKLOG, '测试值')/2 *2) > 0 );

-- [CHANGE-169] p_mmsm_17550/mmsmcf_inq.cpp L104-L113
select (SELECT nvl(ELM_ACT,0) FROM TQMTS25 WHERE heat_no = '' and elm_code = '012' and st_sample_no = '' ) C, (SELECT nvl(ELM_ACT,0) FROM TQMTS25 WHERE heat_no = '' and elm_code = '028' and st_sample_no = '' ) SI, (SELECT nvl(ELM_ACT,0) FROM TQMTS25 WHERE heat_no = '' and elm_code = '055' and st_sample_no = '' ) MN, (SELECT nvl(ELM_ACT,0) FROM TQMTS25 WHERE heat_no = '' and elm_code = '030' and st_sample_no = '' ) P, (SELECT nvl(ELM_ACT,0) FROM TQMTS25 WHERE heat_no = '' and elm_code = '032' and st_sample_no = '' ) S, (SELECT nvl(ELM_ACT,0) FROM TQMTS25 WHERE heat_no = '' and elm_code = '051' and st_sample_no = '' ) V, (SELECT nvl(ELM_ACT,0) FROM TQMTS25 WHERE heat_no = '' and elm_code = '093' and st_sample_no = '' ) NB, (SELECT nvl(ELM_ACT,0) FROM TQMTS25 WHERE heat_no = '' and elm_code = '211' and st_sample_no = '' ) ALS, (SELECT nvl(ELM_ACT,0) FROM TQMTS25 WHERE heat_no = '' and elm_code = '052' and st_sample_no = '' ) CR, (SELECT nvl(ELM_ACT,0) FROM TQMTS25 WHERE heat_no = '' and elm_code = '058' and st_sample_no = '' ) NI from DUAL;

-- [CHANGE-170] p_mmsm_17570/mmsmacshf2_inq.cpp L247-L252
SELECT * FROM ( SELECT CASE WHEN (SELECT PONO FROM TPSSM11 S WHERE S.PONO = T.PONO ) IS NULL and (SELECT PONO FROM TPSSM_PLAN_ST S WHERE S.PONO = T.PONO) IS NULL THEN '8' WHEN T.PONO_SLAB <> ' ' THEN '9' ELSE '3' END AS SLAB_TYPE_OLD,DECODE(substr(TQ01.ORDER_NO,0,1),'A',TQ01.TRNP_MODE_CODE,' ') TRNP_MODE_CODE_1,TQ01.ORDER_THICK,TQ01.PROD_CLASS_DESC, CASE WHEN t2.MAT_NO IS NULL THEN '0' ELSE '1' END need_mend,nvl(t2.MEND_CAUSE, ' ') MEND_CAUSE, T.*,CASE WHEN T.RCV_MAT_FLAG = 'N' THEN ' ' WHEN T.measure_wt = T.receive_weight THEN '1' ELSE '0' END AS avlb_flag1 FROM TMMSM01 T LEFT JOIN TQMOM01 TQ01 ON T.ORDER_NO =TQ01.ORDER_NO LEFT JOIN get_mend_flag t2 ON T.mat_no = t2.MAT_NO WHERE 1 = 1 UNION ALL SELECT CASE WHEN(SELECT PONO FROM TPSSM11 S WHERE S.PONO = T.PONO) IS NULL and(SELECT PONO FROM TPSSM_PLAN_ST S WHERE S.PONO = T.PONO) IS NULL THEN '8' WHEN T.PONO_SLAB <> ' ' THEN '9' ELSE '3' END AS SLAB_TYPE_OLD, DECODE(substr(TQ01.ORDER_NO,0,1),'A',TQ01.TRNP_MODE_CODE,' ') TRNP_MODE_CODE_1,TQ01.ORDER_THICK,TQ01.PROD_CLASS_DESC, CASE WHEN t2.MAT_NO IS NULL THEN '0' ELSE '1' END need_mend,nvl(t2.MEND_CAUSE, ' ') MEND_CAUSE, T.*,CASE WHEN T.RCV_MAT_FLAG = 'N' THEN ' ' WHEN T.measure_wt = T.receive_weight THEN '1' ELSE '0' END AS avlb_flag1 FROM HMMSM01 T LEFT JOIN TQMOM01 TQ01 ON T.ORDER_NO =TQ01.ORDER_NO LEFT JOIN get_mend_flag t2 ON T.mat_no = t2.MAT_NO WHERE 1 = 1 AND USAGE_DECISION <> '3001' ) ORDER BY PROD_TIME DESC;

-- [CHANGE-183] p_mmsm_17570/mmsmwt_del.cpp L75-L75
SELECT MMSM_MATNO_SEQ.NEXTVAL FROM TMMSM25;

-- [CHANGE-184] p_mmsm_17570/mmsmwt_ins.cpp L52-L52
SELECT MMSM_MATNO_SEQ.NEXTVAL FROM TMMSM25;

-- [CHANGE-185] p_mmsm_17570/mmsmwt_upd.cpp L58-L58
SELECT MMSM_MATNO_SEQ.NEXTVAL FROM TMMSM25;

-- [CHANGE-171] p_mmsm_17580/mmsmxmjl_inq.cpp L95-L103
SELECT E.*,R.GRADE_TYPE, ROUND((((CASE WHEN MEND_AFTER_WEIGHT IS NULL THEN 0 ELSE MEND_AFTER_WEIGHT END * CASE WHEN MEND_RATE IS NULL THEN 0 ELSE MEND_RATE END / 100 * 1000) * (18.3 / DECODE(MEND_AFTER_WEIGHT, 0, NULL, MEND_AFTER_WEIGHT)) / 238 * (10.25 / DECODE(decode(trim(MEND_METAL_RATE1), null, 0, MEND_METAL_RATE1), 0, null, MEND_METAL_RATE1))) * CASE WHEN MEND_AFTER_WEIGHT IS NULL THEN 0 ELSE MEND_AFTER_WEIGHT END), 3) AS MEND_WEIGHT1 FROM (SELECT T.*, Q.CODE_DESC_1_CONTENT AS MEND_METAL_RATE1 FROM TMMSM34 T LEFT JOIN (select * from TWMSMZD02 WHERE CODE_CLASS = 'METALRATE') Q ON T.ST_NO = Q.CODE )E LEFT JOIN DA_GRADE_TYPE R ON E.ST_NO = R.GRADE_ID WHERE 1 = 1;

-- [CHANGE-172] p_mmsm_17610/mmsm01a1f2_inq.cpp L117-L123
SELECT A.*,DECODE(substr(TQ01.ORDER_NO,0,1),'A',TQ01.TRNP_MODE_CODE,' ') TRNP_MODE_CODE_1,CASE WHEN t2.MAT_NO IS NULL THEN '0' ELSE '1' END need_mend,nvl(t2.MEND_CAUSE,' ')MEND_CAUSE,TQ01.ORDER_THICK,TQ01.PROD_CLASS_DESC,CASE WHEN A.RCV_MAT_FLAG = 'N' THEN ' ' WHEN A.measure_wt = A.receive_weight THEN '1' ELSE '0' END AS avlb_flag1 SELECT MAT_NO,MAT_SHAPE_FLAG,MAT_STATUS,MAT_THICK,MAT_WIDTH,MAT_LEN,SLAB_HEAD_WIDTH,SLAB_TAIL_WIDTH,MAT_NUM,MAT_WT,MEASURE_WT_FLAG,PONO,HEAT_NO,STOCK_NO,IN_FLAG,ORDER_NO,HOLD_FLAG,PRODUCT_FLAG,ORIGIN_MAT_NO,ST_NO,SG_SIGN,SG_STD,WHOLE_BACKLOG,MSC,PROD_TIME,PSC,MAT_ACT_THICK,MAT_ACT_WIDTH,MAT_ACT_LEN FROM LEFT JOIN TQMOM01 TQ01 ON A.ORDER_NO =TQ01.ORDER_NO LEFT JOIN get_mend_flag t2 ON A.mat_no =t2.MAT_NO WHERE 1 = 1;

-- [CHANGE-359] p_mmsm_17640/cm_0rt801_rcv.cpp L899-L899
select SUBSTR(WHOLE_BACKLOG, INSTR(WHOLE_BACKLOG, '9A') -2, 2) from tqmom03 WHERE ORDER_NO = 'ORDER_NO';

-- [CHANGE-173] p_mmsm_17650/mmsmdrsj_add.cpp L72-L72
SELECT CASE WHEN max(now_row) IS NULL THEN 0 ELSE max(now_row) END FROM TQMTS0RDR where heat_no=''and order_no='';

-- [CHANGE-174] p_mmsm_17660/mmsmcyzjl_inq.cpp L110-L121
select a.PROD_TIME,a.PROD_SHIFT_GROUP,a.HEAT_NO,a.MAT_NO,a.ST_NO,a.MAT_LEN,a.MAT_WIDTH,a.MAT_THICK,a.MAT_WT, CASE WHEN b.SHIFT_GROUP IS NULL THEN c.shift_group ELSE b.SHIFT_GROUP END LOAD_UP_SHIFT_GROUP,CASE WHEN b.OUT_STOCK_TIME IS NULL THEN c.OUT_STOCK_TIME ELSE b.OUT_STOCK_TIME END LOAD_UP_TIME, CASE WHEN substr(b.OUT_STOCK_TIME,9,4)>='0800' AND substr(b.OUT_STOCK_TIME,9,4)<='2000' THEN '白班' ELSE '夜班' END SHIFT_NO, a.HAND_OVER_GROUP AS OUT_STOCK_SHIFT_GROUP, c.LOAD_END_TIME AS OUT_STOCK_TIME, DECODE(TRAN_END_TIME,' ',TRAN_TIME,TRAN_END_TIME)TRAN_TIME ,B.OPERATOR EMP_NAME, a.LGORT, CASE WHEN b.UNLOAD_CODE IS NULL THEN c.UNLOAD_CODE ELSE b.UNLOAD_CODE END UNLOAD_CODE, CASE WHEN b.TRUCK_NO IS NULL THEN c.TRUCK_NO ELSE b.TRUCK_NO END TRUCK_NO, D.CODE_DESC_1_CONTENT, b.OPERATOR, GUIDE_DEST, STOCK_L2, C.REMARK, a.UNIT_CODE,a.c_div from vmmsm01 a left join vwmsm12 b on a.LOAD_SCHEME_NO = b.LOAD_SCHEME_NO and a.MAT_NO = b.MAT_NO left join twmsm61 c on a.PRACTICE_NO = c.PRACTICE_NO and a.MAT_NO = c.MAT_NO left join twmsmzd02 d on d.CODE = b.TRUCK_NO and d.code_class='WM01' where 1=1 AND A.LOAD_SCHEME_NO!=' ';-- [多行拼接语句(mmsmdbdc_inq DECODE→CASE),已在源码逐块验证,请参考台账和源码注释];

-- [CHANGE-176] p_mmsm_17660/mmsmhsljl_inq.cpp L89-L98
SELECT E.*,R.GRADE_TYPE,R.grade_name,W.DEV_CODE, ROUND((((CASE WHEN e.MEND_AFTER_WEIGHT IS NULL THEN 0 ELSE e.MEND_AFTER_WEIGHT END * CASE WHEN MEND_RATE IS NULL THEN 0 ELSE MEND_RATE END / 100 * 1000) * (18.3 / DECODE(e.MEND_AFTER_WEIGHT, 0, NULL, e.MEND_AFTER_WEIGHT)) / 238 * (10.25 / DECODE(decode(trim(MEND_METAL_RATE1), null, 0, MEND_METAL_RATE1), 0, null, MEND_METAL_RATE1))) * CASE WHEN e.MEND_AFTER_WEIGHT IS NULL THEN 0 ELSE e.MEND_AFTER_WEIGHT END), 3) AS MEND_WEIGHT1 FROM (SELECT T.*, Q.CODE_DESC_1_CONTENT AS MEND_METAL_RATE1 FROM TMMSM34 T LEFT JOIN(select * from TWMSMZD02 WHERE CODE_CLASS = 'METALRATE') Q ON T.ST_NO = Q.CODE)E LEFT JOIN DA_GRADE_TYPE R ON E.ST_NO = R.GRADE_ID LEFT JOIN TMMSM01 W ON E.MAT_NO = W.MAT_NO WHERE 1 = 1;

-- [CHANGE-177] p_mmsm_17660/mmsmlcbgx_inq.cpp L132-L132
AND to_char(to_date(CASE WHEN trim(AOD_BOF_E_DTIME) IS NULL THEN '1999-01-01 00:01:01' ELSE AOD_BOF_E_DTIME END,'yyyy-mm-dd hh24:mi:ss'),'yyyyMMddhhmiss')>= '测试值';

-- [CHANGE-178] p_mmsm_17660/mmsmlcbgx_inq.cpp L142-L142
AND to_char(to_date(CASE WHEN trim(AOD_BOF_E_DTIME) IS NULL THEN '1999-01-01 00:01:01' ELSE AOD_BOF_E_DTIME END,'yyyy-mm-dd hh24:mi:ss'),'yyyyMMddhhmiss')<= '测试值';

-- [CHANGE-179] p_mmsm_17660/mmsmlcbqx_inq.cpp L133-L133
AND to_char(to_date(CASE WHEN trim(AOD_BOF_E_DTIME) IS NULL THEN '1999-01-01 00:01:01' ELSE AOD_BOF_E_DTIME END,'yyyy-mm-dd hh24:mi:ss'),'yyyyMMddhhmiss')>= '测试值';

-- [CHANGE-180] p_mmsm_17660/mmsmlcbqx_inq.cpp L143-L143
AND to_char(to_date(CASE WHEN trim(AOD_BOF_E_DTIME) IS NULL THEN '1999-01-01 00:01:01' ELSE AOD_BOF_E_DTIME END,'yyyy-mm-dd hh24:mi:ss'),'yyyyMMddhhmiss')<= '测试值';

-- [CHANGE-181] p_mmsm_17660/mmsmqxdc_inq.cpp L159-L198
SELECT T.SLAB_CUT_TIME,T.PROD_SHIFT_GROUP,T.HEAT_NO,T.BATCH,' ' WL_CODE,' ' WL_DESCRIPTION,T.ST_NO,T.MAT_ACT_LEN,T.MAT_ACT_WIDTH,T.MAT_ACT_THICK,T.RECEIVE_WEIGHT,T.GUIDE_DEST,T.CASTING_PRE_JUDGMENT, T.CASTING_PURPOSE, T.SURF_QUALITY, DECODE(T.RECEIVE_WEIGHT, 0, 'N', 'Y') RECEIVE_STATUS, T.RECV_MAT_TIME, DECODE(T.RECEIVE_WEIGHT, 0, 'N', 'S') SPECIFIC_SEND, DECODE(T.C_STATESIGN, '3', 'S', '1', 'W', 'N') C_STATESIGN, T.USAGE_DECISION, tm34.MEND_SHIFT as PROD_GROUP_TMMSM34, CASE WHEN T.C_DELIVERY_STOCK = '6235' THEN 'C0' WHEN(SUBSTR(T.MAT_NO, 0, 2) = 'A0' OR SUBSTR(T.MAT_NO, 0, 2) = 'A1' OR SUBSTR(T.MAT_NO, 0, 2) = 'A2' OR SUBSTR(T.MAT_NO, 0, 2) = 'A3' OR SUBSTR(T.MAT_NO, 0, 2) = 'A5' OR SUBSTR(T.MAT_NO, 0, 2) = 'A5' OR SUBSTR(T.MAT_NO, 0, 2) = 'A6' OR SUBSTR(T.MAT_NO, 0, 2) = 'B0' OR SUBSTR(T.MAT_NO, 0, 2) = 'B1' OR SUBSTR(T.MAT_NO, 0, 2) = 'B2' OR SUBSTR(T.MAT_NO, 0, 2) = 'B9') AND tm34.mat_no is null AND TM34_1.MAT_NO <>' ' AND TM34_1.MEND_AFTER_WEIGHT <> tm34_1.MEND_BEFORE_WEIGHT THEN 'B0' WHEN T.ARCHIVE_TIME <>' ' AND T.MEND_FLAG = '0' AND T.C_DIV='1' THEN 'A0' else tm34.MEND_SET end MEND_SET, tm34.MEND_AFTER_WEIGHT MEND_AFTER_WEIGHT, tm34.START_TIME XM_TIME, tm34.MEND_INNER_MODE MEND_INNER_MODE, tm34.MEND_OUTER_MODE MEND_OUTER_MODE, tm34.MEND_CALCULATE_RATE, tm34.MEND_TOTAL_TIME MEND_TOTAL_TIME, T.TRAN_END_TIME, T.HAND_OVER_GROUP JK_SHIFT_GROUP, t.DST_STOCK_CODE, t.mat_act_wt, CASE WHEN TW62.LOAD_CODE_FACTORY IS NULL THEN TWM41.C_SENDDEPT ELSE TW62.LOAD_CODE_FACTORY END RETURNPLANT,CASE WHEN TW62.SHIFT_GROUP IS NULL THEN TWM41.C_GROUP ELSE TW62.SHIFT_GROUP END SHIFTRETURN, CASE WHEN TW62.UNLOAD_END_TIME IS NULL THEN TWM41.T_INSTOCKTIME ELSE TW62.UNLOAD_END_TIME END RETURNDATE, CASE WHEN TW62.BACK1 IS NULL THEN TWM41.C_QULITYTYPE ELSE TW62.BACK1 END RETURNREASON, tm39.RECUT_DATE GQ_RECUT_DATE, tm39.PROD_SHIFT_GROUP GQ_PROD_GROUP, tm39.CUTTING_TYPE GQ_CUTTING_TYPE, case when length2(SLAB_NO)>=20 then to_number(decode(substr(T.slab_no, length(T.slab_no) - 2, 3), ' ', 0,substr(T.slab_no, length(T.slab_no) - 2, 3))) end CAST_DIV_NO, t.DEV_CODE, (SELECT PROD_SHIFT_GROUP FROM TMMSM36 WHERE MAT_NO = T.MAT_NO) PROD_GROUP_SB, t.HOT_SEND_FLAG, t.ZL_REASON_DESC, t.JUDGE_RESULT_1, t.REMARK,CASE WHEN TWM12.UNLOAD_CODE_AREA IS NULL THEN twm61.UNLOAD_CODE_AREA ELSE TWM12.UNLOAD_CODE_AREA END UNLOAD_CODE_AREA, CASE WHEN TWM12.TRUCK_NO IS NULL THEN twm61.TRUCK_NO ELSE TWM12.TRUCK_NO END TRUCK_NO, t.STOCK_L2, t.ORDER_NO, t.mat_no, (SELECT DELIVY_DATE from tqmom01 where ORDER_NO = T.ORDER_NO) DELIVY_DATE, (SELECT ORDER_THICK from tqmom01 where ORDER_NO = T.ORDER_NO) ORDER_THICK, t.SG_GRADE_1, (SELECT GRADE_TYPE FROM DA_GRADE_TYPE WHERE GRADE_ID = T.ST_NO) GRADE_TYPE, (SELECT SCRAP_TYPE FROM DA_GRADE_TYPE WHERE GRADE_ID = T.ST_NO) SCRAP_TYPE, t.slab_no, tm34.GRINDING_START_TIME, tm34.GRINDING_OUTER_END_TIME, decode(tm34.MEND_BEFORE_UPPER_TEMP, 0, tm34.MEND_AFTER_UPPER_TEMP, tm34.MEND_BEFORE_UPPER_TEMP) MEND_BEFORE_TEMP, decode(tm34.MEND_BEFORE_BOTTOM_TEMP, 0, tm34.MEND_AFTER_BOTTOM_TEMP, MEND_BEFORE_BOTTOM_TEMP) MEND_AFTER_TEMP, t.TRUCK_NO as CHEHAO, T.STOCK_PLACE_NO, T.STOCK_PLACE_NO BP_TOCK_L2, TM34.REC_REVISE_TIME REC_REVISE_TIME, ' ' ORDER_NO_DD, DECODE(SUBSTR(T.ST_NO, 0, 1), 1, '不锈钢', '碳钢') ST_NO_TYPE_1, CASE WHEN SUBSTR(T.ST_NO, 0, 2) = '1A' OR SUBSTR(T.ST_NO, 0, 2) = '1D' THEN '镍钢' WHEN SUBSTR(T.ST_NO, 0, 2) = '1M' OR SUBSTR(T.ST_NO, 0, 2) = '1F' THEN '铬钢' WHEN SUBSTR(T.ST_NO, 0, 1) = '1' THEN '不锈钢' else '碳钢' end as ST_NO_TYPE_2, CASE WHEN TWM12.SHIFT_GROUP IS NULL THEN twm61.SHIFT_GROUP ELSE TWM12.SHIFT_GROUP END ZC_PROD_GROUP, CASE WHEN TWM12.OUT_STOCK_TIME IS NULL THEN twm61.LOAD_END_TIME ELSE TWM12.OUT_STOCK_TIME END ZC_TIME, T.C_DELIVERY_STOCK, DECODE(T.LOGISTICS_STATUS, '2', 'W', '3', 'Y', 'N') LOGISTICS_STATUS, DECODE(T.LGORT, '6242', '成品库', '6246', '修磨库') VALUE_TYPE, T.PRODUCT_FLAG , case when STOCK_L2 in('CS-HSM', 'SS-HSM', 'HF') THEN '2250' when DST_STOCK_CODE = 'WXK104' THEN '钢坯库' when DST_STOCK_CODE in('WXK101', 'WXK102', 'WXK103') THEN '储运站' when DST_STOCK_CODE in('635003') THEN '1549' when DST_STOCK_CODE in('639002') THEN '4300' when DST_STOCK_CODE in('622002') THEN '南区' when DST_STOCK_CODE in('631003') THEN '型材' when DST_STOCK_CODE in('TBZX01') THEN '太北' else '二钢北区' end location,CASE WHEN t2.MAT_NO IS NULL THEN '0' ELSE '1' END need_mend,nvl(t2.OFFLINE_FLAG, ' ') OFFLINE_FLAG,nvl(t2.MEND_CAUSE, ' ') MEND_CAUSE,nvl(t2.OFFLINE_REASON, ' ') OFFLINE_REASON FROM(SELECT MAT_NO, SLAB_CUT_TIME, PROD_SHIFT_GROUP, HEAT_NO, BATCH, ST_NO, MAT_ACT_LEN, MAT_ACT_WIDTH, MAT_ACT_THICK, RECEIVE_WEIGHT, GUIDE_DEST, CASTING_PRE_JUDGMENT, CASTING_PURPOSE, SURF_QUALITY, RECV_MAT_TIME, C_STATESIGN, USAGE_DECISION, ARCHIVE_TIME, MEND_FLAG, C_DELIVERY_STOCK, TRAN_END_TIME, PRACTICE_NO, DST_STOCK_CODE, mat_act_wt, slab_no, DEV_CODE, HOT_SEND_FLAG, ZL_REASON_DESC, JUDGE_RESULT_1, REMARK, UNLOAD_CODE, ORDER_NO, SG_GRADE_1, TRUCK_NO, STOCK_PLACE_NO, STOCK_L2, LOAD_SCHEME_NO, LOGISTICS_STATUS, LGORT, PRODUCT_FLAG, HAND_OVER_GROUP,C_DIV FROM TMMSM01 where 1 = 1 UNION ALL SELECT MAT_NO, SLAB_CUT_TIME, PROD_SHIFT_GROUP, HEAT_NO, BATCH, ST_NO, MAT_ACT_LEN, MAT_ACT_WIDTH, MAT_ACT_THICK, RECEIVE_WEIGHT, GUIDE_DEST, CASTING_PRE_JUDGMENT, CASTING_PURPOSE, SURF_QUALITY, RECV_MAT_TIME, C_STATESIGN, USAGE_DECISION, ARCHIVE_TIME, MEND_FLAG, C_DELIVERY_STOCK, TRAN_END_TIME, PRACTICE_NO, DST_STOCK_CODE, mat_act_wt, slab_no, DEV_CODE, HOT_SEND_FLAG, ZL_REASON_DESC, JUDGE_RESULT_1, REMARK, UNLOAD_CODE, ORDER_NO, SG_GRADE_1, TRUCK_NO, STOCK_PLACE_NO, STOCK_L2, LOAD_SCHEME_NO, LOGISTICS_STATUS, LGORT, PRODUCT_FLAG, HAND_OVER_GROUP FROM HMMSM01 where 1 = 1 AND(C_DELIVERY_STOCK = ' ' or C_DELIVERY_STOCK = '6245') ) T LEFT JOIN(SELECT PROD_SHIFT_GROUP, MEND_SHIFT,MEND_SET, MEND_AFTER_WEIGHT, START_TIME, MEND_INNER_MODE, MEND_OUTER_MODE, MEND_CALCULATE_RATE, MEND_TOTAL_TIME, GRINDING_START_TIME, GRINDING_OUTER_END_TIME, MEND_BEFORE_UPPER_TEMP, MEND_AFTER_UPPER_TEMP, MEND_BEFORE_BOTTOM_TEMP, MEND_AFTER_BOTTOM_TEMP, REC_REVISE_TIME, mat_no FROM( SELECT ROW_NUMBER() over(PARTITION BY MAT_NO ORDER BY REC_CREATE_TIME DESC) TM34_MAX, PROD_SHIFT_GROUP,MEND_SHIFT, MEND_SET, MEND_AFTER_WEIGHT, START_TIME, MEND_INNER_MODE, MEND_OUTER_MODE, MEND_CALCULATE_RATE, MEND_TOTAL_TIME, GRINDING_START_TIME, GRINDING_OUTER_END_TIME, MEND_BEFORE_UPPER_TEMP, MEND_AFTER_UPPER_TEMP, MEND_BEFORE_BOTTOM_TEMP, MEND_AFTER_BOTTOM_TEMP, REC_REVISE_TIME, mat_no FROM TMMSM34) WHERE TM34_MAX = 1) tm34 on t.mat_no = tm34.MAT_NO LEFT JOIN(select RECUT_DATE, PROD_SHIFT_GROUP, CUTTING_TYPE, MAT_no from(SELECT ROW_NUMBER() over(PARTITION BY MAT_NO ORDER BY RESUME_SEQ_NO DESC) TM39max, RECUT_DATE, PROD_SHIFT_GROUP, CUTTING_TYPE, MAT_NO from tmmsm39) where TM39max = '1') TM39 ON t.mat_no = tm39.mat_no LEFT JOIN(select LOAD_CODE_FACTORY, SHIFT_GROUP, MAT_NO, LOAD_END_TIME, RETURNREASON,UNLOAD_END_TIME,BACK1 from(SELECT ROW_NUMBER() over(PARTITION BY MAT_NO ORDER BY REC_CREATE_TIME DESC) tw62_max, LOAD_CODE_FACTORY, mat_no, SHIFT_GROUP, LOAD_END_TIME, RETURNREASON,UNLOAD_END_TIME,BACK1 from (SELECT MAT_NO,REC_CREATE_TIME,LOAD_CODE_FACTORY,SHIFT_GROUP,LOAD_END_TIME,RETURNREASON,UNLOAD_END_TIME,BACK1 FROM TWMSM62 WHERE UNLOAD_CODE_FACTORY = '6240' AND MAT_NO != ' ' UNION SELECT MAT_NO,REC_CREATE_TIME,UNLOAD_CODE_FACTORY,BACK3,UNLOAD_END_TIME,BACK4,UNLOAD_END_TIME,BACK1 FROM TWMSM13)) where tw62_max = '1') TW62 ON T.MAT_NO = TW62.MAT_NO LEFT JOIN(SELECT MAT_NO, MEND_BEFORE_WEIGHT, MEND_AFTER_WEIGHT FROM(SELECT ROW_NUMBER() over(PARTITION BY MAT_NO ORDER BY REC_CREATE_TIME DESC) TM34_1MAX, MAT_NO, MEND_BEFORE_WEIGHT, MEND_AFTER_WEIGHT FROM TMMSM34_1) WHERE TM34_1MAX = '1') tm34_1 on t.mat_no = tm34_1.MAT_NO LEFT JOIN vWMSM12 TWM12 ON T.MAT_NO = TWM12.MAT_NO AND TWM12.LOAD_SCHEME_NO = T.LOAD_SCHEME_NO LEFT JOIN (select MAT_NO,OFFLINE_FLAG,MEND_CAUSE,OFFLINE_REASON from get_offline_flag) t2 ON t.mat_no =t2.MAT_NO LEFT JOIN twmsm61 TWM61 ON T.MAT_NO = TWM61.MAT_NO AND TWM61.PRACTICE_NO = T.PRACTICE_NO AND TWM61.LOAD_CODE!='624002065' LEFT JOIN (SELECT C_BATCHUNIT, I_RESERVECOL4,C_STATESIGN,C_SENDDEPT,C_GROUP,T_INSTOCKTIME,C_QULITYTYPE FROM(SELECT ROW_NUMBER() over(PARTITION BY C_BATCHUNIT ORDER BY REC_CREATE_TIME DESC) TW41_1MAX,C_BATCHUNIT, I_RESERVECOL4, C_STATESIGN, C_SENDDEPT, C_GROUP, T_INSTOCKTIME, C_QULITYTYPE FROM TWM41DJ WHERE I_RESERVECOL4 = '1' AND C_STATESIGN = '2') WHERE TW41_1MAX = '1') TWM41 ON T.MAT_NO = TWM41.C_BATCHUNIT WHERE T.MAT_ACT_WT > 0;-- [多行拼接续行,已在源码验证];

-- [CHANGE-163] Server/MMSM/p_mmsm_17520/mmsmis02_inq.cpp (2026-09-08 追加,HR 口径①,变量以测试值代入;未执行)
select DATEDIFF(SECOND, TO_TIMESTAMP('20240904143000','YYYYMMDDHH24MISS'), TO_TIMESTAMP('20240904143000','YYYYMMDDHH24MISS')) / 3600 from DUAL;

-- [CHANGE-164] Server/MMSM/p_mmsm_17520/mmsmis02_inqa.cpp (2026-09-08 追加,HR 口径①,变量以测试值代入;未执行)
select DATEDIFF(SECOND, TO_TIMESTAMP('20240904143000','YYYYMMDDHH24MISS'), TO_TIMESTAMP('20240904143000','YYYYMMDDHH24MISS')) / 3600 from DUAL;

-- [CHANGE-165] Server/MMSM/p_mmsm_17520/mmsmis02a1_inq.cpp (2026-09-08 追加,HR 口径①,变量以测试值代入;未执行)
select DATEDIFF(SECOND, TO_TIMESTAMP('20240904143000','YYYYMMDDHH24MISS'), CURRENT_TIMESTAMP) / 3600 from DUAL;

-- [CHANGE-166] Server/MMSM/p_mmsm_17520/mmsmis02a1_inq.cpp (2026-09-08 追加,HR 口径①,变量以测试值代入;未执行)
select DATEDIFF(SECOND, TO_TIMESTAMP('20240904143000','YYYYMMDDHH24MISS'), TO_TIMESTAMP('20240904143000','YYYYMMDDHH24MISS')) / 3600 from DUAL;

-- [CHANGE-167] Server/MMSM/p_mmsm_17520/mmsmis02a1_inqa.cpp (2026-09-08 追加,HR 口径①,变量以测试值代入;未执行)
select DATEDIFF(SECOND, TO_TIMESTAMP('20240904143000','YYYYMMDDHH24MISS'), CURRENT_TIMESTAMP) / 3600 from DUAL;

-- [CHANGE-168] Server/MMSM/p_mmsm_17520/mmsmis02a1_inqa.cpp (2026-09-08 追加,HR 口径①,变量以测试值代入;未执行)
select DATEDIFF(SECOND, TO_TIMESTAMP('20240904143000','YYYYMMDDHH24MISS'), TO_TIMESTAMP('20240904143000','YYYYMMDDHH24MISS')) / 3600 from DUAL;
