-- SM00 E2 验证脚本(自动生成,需在 DM8 环境执行)
-- 语句数:3;生成日期:2026-09-06
-- 注意:仅验证语法可执行性(SELECT 返回列/类型),不验证结果等价性
-- 期望结果:全部语句编译通过,SELECT 语句返回结果集

-- [CHANGE-266] libSM00/f_sm00_plan_mat.cpp L132-L137
SELECT CASE WHEN TRIM(A.BILL_OF_LADING_NO) IS NULL OR TRIM(A.BILL_OF_LADING_NO) = '' THEN A.BILL_OF_LADING_NO_1 ELSE A.BILL_OF_LADING_NO END AS BILL_OF_LADING_NO, CASE WHEN A.ORDER_NO_1 IS NULL THEN B.ORDER_NO ELSE A.ORDER_NO_1 END AS ORDER_NO, A.OLD_ORDER_NO,A.PROD_CNAME,A.RED_FLAG, (CASE WHEN B.MAT_SHAPE_FLAG='7' THEN B.LAYERNO || B.ROWNO || B.COLUMN_NO ELSE B.LAYERNO || B.COLUMN_NO END) STOCK_PLACE_POSITION , B.* FROM B ,() A WHERE B.MAT_NO = A.MAT_NO;

-- [CHANGE-267] libSM00/f_sm00_plan_mat.cpp L192-L197
SELECT CASE WHEN TRIM(A.BILL_OF_LADING_NO) IS NULL OR TRIM(A.BILL_OF_LADING_NO) = '' THEN A.BILL_OF_LADING_NO_1 ELSE A.BILL_OF_LADING_NO END AS BILL_OF_LADING_NO, CASE WHEN A.ORDER_NO_1 IS NULL THEN B.ORDER_NO ELSE A.ORDER_NO_1 END AS ORDER_NO, A.OLD_ORDER_NO,A.PROD_CNAME,A.RED_FLAG, (CASE WHEN B.MAT_SHAPE_FLAG='7' THEN B.LAYERNO || B.ROWNO || B.COLUMN_NO ELSE B.LAYERNO || B.COLUMN_NO END) STOCK_PLACE_POSITION , B.* FROM B ,() A WHERE B.MAT_NO = A.MAT_NO;

-- [CHANGE-268] libSM00/f_sm00_plan_mat.cpp L236-L237
SELECT A.BILL_OF_LADING_NO_1 AS BILL_OF_LADING_NO,CASE WHEN A.ORDER_NO_1 IS NULL THEN B.ORDER_NO ELSE A.ORDER_NO_1 END AS ORDER_NO ,A.OLD_ORDER_NO,A.PROD_CNAME,A.RED_FLAG,B.*;

