-- 达梦 DM8 方言支持探针：全部只依赖 DUAL，不需要任何业务表
-- 用途：断网(VPN 内网)环境下验证转换规则 T1—T15、保留白名单与 HR-001 时间格式
-- 判读：每条语句的 V 列是预期可读的结果；失败即为该写法在当前 DM8 上不被支持
--       NEG1 / NEG2 是负向对照，必须失败；若它们显示"成功"，说明校验器不可信

-- [CHANGE-PROBE-01] T1 辅助表 DUAL
SELECT 'T1-DUAL' AS PROBE_ID, 1 AS V FROM DUAL;

-- [CHANGE-PROBE-02] T2 日期与整数直接加减(以天为单位)
SELECT 'T2-DATE-INT' AS PROBE_ID, TO_CHAR(CURRENT_DATE + 1 - 1, 'YYYYMMDD') AS V FROM DUAL;

-- [CHANGE-PROBE-03] T3 天数差 DATEDIFF(DAY,起点,终点)；跨日应为 1
SELECT 'T3-DATEDIFF-FWD' AS PROBE_ID, DATEDIFF(DAY, TO_TIMESTAMP('20260904235959','YYYYMMDDHH24MISS'), TO_TIMESTAMP('20260905000001','YYYYMMDDHH24MISS')) AS V FROM DUAL;

-- [CHANGE-PROBE-04] T3 反向(终点早于起点)方向应为 -1
SELECT 'T3-DATEDIFF-BACK' AS PROBE_ID, DATEDIFF(DAY, TO_TIMESTAMP('20260905000001','YYYYMMDDHH24MISS'), TO_TIMESTAMP('20260904235959','YYYYMMDDHH24MISS')) AS V FROM DUAL;

-- [CHANGE-PROBE-05] T3 月末边界 08-31 23:59:59 -> 09-01 00:00:00 应为 1
SELECT 'T3-DATEDIFF-MONTHEND' AS PROBE_ID, DATEDIFF(DAY, TO_TIMESTAMP('20260831235959','YYYYMMDDHH24MISS'), TO_TIMESTAMP('20260901000000','YYYYMMDDHH24MISS')) AS V FROM DUAL;

-- [CHANGE-PROBE-06] T3 闰日边界 2028-02-28 23:59:59 -> 02-29 00:00:00 应为 1
SELECT 'T3-DATEDIFF-LEAP' AS PROBE_ID, DATEDIFF(DAY, TO_TIMESTAMP('20280228235959','YYYYMMDDHH24MISS'), TO_TIMESTAMP('20280229000000','YYYYMMDDHH24MISS')) AS V FROM DUAL;

-- [CHANGE-PROBE-07] HR-002 口径① 分钟换算：2 秒应截断为 0
SELECT 'HR002-SEC2MIN' AS PROBE_ID, DATEDIFF(SECOND, TO_TIMESTAMP('20260904085959','YYYYMMDDHH24MISS'), TO_TIMESTAMP('20260904090001','YYYYMMDDHH24MISS')) / 60 AS V FROM DUAL;

-- [CHANGE-PROBE-08] HR-002 口径① 小时换算：2 秒应截断为 0
SELECT 'HR002-SEC2HOUR' AS PROBE_ID, DATEDIFF(SECOND, TO_TIMESTAMP('20260904085959','YYYYMMDDHH24MISS'), TO_TIMESTAMP('20260904090001','YYYYMMDDHH24MISS')) / 3600 AS V FROM DUAL;

-- [CHANGE-PROBE-09] HR-002 口径① 天换算：2026-02-01 -> 03-01 应为 28
SELECT 'HR002-DAYS28' AS PROBE_ID, DATEDIFF(SECOND, TO_TIMESTAMP('20260201000000','YYYYMMDDHH24MISS'), TO_TIMESTAMP('20260301000000','YYYYMMDDHH24MISS')) / 86400 AS V FROM DUAL;

-- [CHANGE-PROBE-10] HR-002 口径① 负时差截断方向(原始秒数，应为负数)
SELECT 'HR002-NEG-SEC' AS PROBE_ID, DATEDIFF(SECOND, TO_TIMESTAMP('20260905100000','YYYYMMDDHH24MISS'), TO_TIMESTAMP('20260905093000','YYYYMMDDHH24MISS')) AS V FROM DUAL;

-- [CHANGE-PROBE-11] HR-002 口径① 负时差下 /3600 的截断方向(重点观察)
SELECT 'HR002-NEG-HOUR' AS PROBE_ID, DATEDIFF(SECOND, TO_TIMESTAMP('20260905100000','YYYYMMDDHH24MISS'), TO_TIMESTAMP('20260905093000','YYYYMMDDHH24MISS')) / 3600 AS V FROM DUAL;

-- [CHANGE-PROBE-12] T4 DECODE 对 NULL 的匹配行为(基线观测)
SELECT 'T4-DECODE-NULL' AS PROBE_ID, DECODE(NULL, NULL, 'match', 'nomatch') AS V FROM DUAL;

-- [CHANGE-PROBE-13] T4 目标写法 CASE 对 NULL 的匹配
SELECT 'T4-CASE-NULL' AS PROBE_ID, CASE WHEN CAST(NULL AS VARCHAR(10)) IS NULL THEN 'match' ELSE 'nomatch' END AS V FROM DUAL;

-- [CHANGE-PROBE-14] T12 空串是否等同 NULL(关键环境参数，直接决定 CHANGE-388 类改写是否需要)
SELECT 'T12-EMPTY-IS-NULL' AS PROBE_ID, CASE WHEN '' IS NULL THEN 'empty-is-null' ELSE 'empty-distinct' END AS V FROM DUAL;

-- [CHANGE-PROBE-15] T12 DECODE 对空串的匹配行为
SELECT 'T12-DECODE-EMPTY' AS PROBE_ID, DECODE('', NULL, 'match', 'nomatch') AS V FROM DUAL;

-- [CHANGE-PROBE-16] HR-003 / CHANGE-388 三种空白的判定写法
SELECT 'HR003-TRIM-SPACE' AS PROBE_ID, COALESCE(LENGTH(TRIM('   ')), 0) AS V FROM DUAL;

-- [CHANGE-PROBE-17] T5 标量 MAX 的 NULL 守卫(双非空分支可正常求值)
SELECT 'T5-GREATEST-OK' AS PROBE_ID, CASE WHEN 1 IS NULL OR 2 IS NULL THEN NULL ELSE GREATEST(1, 2) END AS V FROM DUAL;

-- [CHANGE-PROBE-18] T5 标量 MAX 的 NULL 守卫(NULL 分支应返回 NULL)
SELECT 'T5-GREATEST-NULL' AS PROBE_ID, CASE WHEN 1 IS NULL OR CAST(NULL AS INT) IS NULL THEN NULL ELSE GREATEST(1, CAST(NULL AS INT)) END AS V FROM DUAL;

-- [CHANGE-PROBE-19] T6 ROWNUM 作列别名 RN
SELECT 'T6-ROWNUM-ALIAS' AS PROBE_ID, ROWNUM AS RN FROM DUAL;

-- [CHANGE-PROBE-20] T8 序列伪列 + FROM DUAL 的写法形态(占位序列名需替换为本库真实序列)
SELECT 'T8-SEQ-FORM' AS PROBE_ID, 'SELECT <SEQ>.NEXTVAL FROM DUAL' AS V FROM DUAL;

-- [CHANGE-PROBE-21] T9 VALUE 改为 NVL
SELECT 'T9-NVL' AS PROBE_ID, NVL(CAST(NULL AS VARCHAR(10)), 'x') AS V FROM DUAL;

-- [CHANGE-PROBE-22] T10 SUBSTR 位置 1(目标写法)
SELECT 'T10-SUBSTR-1' AS PROBE_ID, SUBSTR('abcdef', 1, 3) AS V FROM DUAL;

-- [CHANGE-PROBE-23] T10 SUBSTR 位置 0 的边界行为(观测 DM 实际语义)
SELECT 'T10-SUBSTR-0' AS PROBE_ID, SUBSTR('abcdef', 0, 3) AS V FROM DUAL;

-- [CHANGE-PROBE-24] T11/T13 小数天：加 1 小时
SELECT 'T11-HOUR' AS PROBE_ID, TO_CHAR(CURRENT_TIMESTAMP + 1.0/24, 'YYYYMMDDHH24MISS') AS V FROM DUAL;

-- [CHANGE-PROBE-25] T13 小数天：加 1 分钟
SELECT 'T13-MINUTE' AS PROBE_ID, TO_CHAR(CURRENT_TIMESTAMP + 1.0/1440, 'YYYYMMDDHH24MISS') AS V FROM DUAL;

-- [CHANGE-PROBE-26] T13 小数天：加 1 秒
SELECT 'T13-SECOND' AS PROBE_ID, TO_CHAR(CURRENT_TIMESTAMP + 1.0/86400, 'YYYYMMDDHH24MISS') AS V FROM DUAL;

-- [CHANGE-PROBE-27] T14 日期时间寄存器
SELECT 'T14-CURRENT-DATE' AS PROBE_ID, TO_CHAR(CURRENT_DATE, 'YYYYMMDD') AS V FROM DUAL;

-- [CHANGE-PROBE-28] T14 当前模式名
SELECT 'T14-CURRENT-SCHEMA' AS PROBE_ID, CURRENT_SCHEMA AS V FROM DUAL;

-- [CHANGE-PROBE-29] T15 POSSTR 改为 INSTR；未找到时应返回 0
SELECT 'T15-INSTR-FOUND' AS PROBE_ID, INSTR('hello world', 'o') AS V FROM DUAL;

-- [CHANGE-PROBE-30] T15 INSTR 未找到返回 0
SELECT 'T15-INSTR-MISS' AS PROBE_ID, INSTR('hello world', 'zz') AS V FROM DUAL;

-- [CHANGE-PROBE-31] HR-001 14 位紧凑时间串解析
SELECT 'HR001-TO_TIMESTAMP' AS PROBE_ID, TO_TIMESTAMP('20260904143000','YYYYMMDDHH24MISS') AS V FROM DUAL;

-- [CHANGE-PROBE-32] 白名单 LISTAGG + WITHIN GROUP(DISTINCT)
SELECT 'WL-LISTAGG' AS PROBE_ID, LISTAGG(DISTINCT X, '*') WITHIN GROUP (ORDER BY X) AS V FROM (SELECT 'b' X FROM DUAL UNION ALL SELECT 'a' X FROM DUAL) T;

-- [CHANGE-PROBE-33] 白名单 CONNECT BY 层次查询
SELECT 'WL-CONNECTBY' AS PROBE_ID, COUNT(*) AS V FROM (SELECT LEVEL L FROM DUAL CONNECT BY LEVEL <= 3);

-- [CHANGE-PROBE-34] 白名单 REGEXP_SUBSTR
SELECT 'WL-REGEXP-SUBSTR' AS PROBE_ID, REGEXP_SUBSTR('abc123', '[0-9]+') AS V FROM DUAL;

-- [CHANGE-PROBE-35] 白名单 REGEXP_LIKE
SELECT 'WL-REGEXP-LIKE' AS PROBE_ID, CASE WHEN REGEXP_LIKE('abc123', '[0-9]+') THEN 'yes' ELSE 'no' END AS V FROM DUAL;

-- [CHANGE-PROBE-36] 白名单 LENGTH2(中文按字符长度)
SELECT 'WL-LENGTH2' AS PROBE_ID, LENGTH2('中文') AS V FROM DUAL;

-- [CHANGE-PROBE-37] 白名单 LENGTHB(中文按字节长度)
SELECT 'WL-LENGTHB' AS PROBE_ID, LENGTHB('中文') AS V FROM DUAL;

-- [CHANGE-PROBE-38] 白名单 SYS_GUID
SELECT 'WL-SYSGUID' AS PROBE_ID, SYS_GUID() AS V FROM DUAL;

-- [CHANGE-PROBE-39] 白名单 FETCH FIRST n ROWS ONLY
SELECT 'WL-FETCHFIRST' AS PROBE_ID, X AS V FROM (SELECT 1 X FROM DUAL UNION ALL SELECT 2 X FROM DUAL) T ORDER BY X FETCH FIRST 1 ROWS ONLY;

-- [CHANGE-PROBE-40] 白名单 MINUS 集合运算
SELECT 'WL-MINUS' AS PROBE_ID, COUNT(*) AS V FROM ((SELECT 1 X FROM DUAL UNION ALL SELECT 2 X FROM DUAL) MINUS (SELECT 1 X FROM DUAL));

-- [CHANGE-PROBE-41] 白名单 PIVOT
SELECT 'WL-PIVOT' AS PROBE_ID, COUNT(*) AS V FROM (SELECT * FROM (SELECT 'a' K, 1 N FROM DUAL UNION ALL SELECT 'b' K, 2 N FROM DUAL) PIVOT (SUM(N) FOR K IN ('a' AS A, 'b' AS B)));

-- [CHANGE-PROBE-42] 白名单 CAST/ROUND/TO_CHAR/LPAD
SELECT 'WL-CAST-ROUND' AS PROBE_ID, TO_CHAR(ROUND(1.267, 2)) || '|' || LPAD('7', 3, '0') AS V FROM DUAL;

-- [CHANGE-PROBE-43] 白名单 Oracle (+) 外连接(失败则回退 ANSI JOIN)
SELECT 'WL-ORACLE-OUTERJOIN' AS PROBE_ID, COUNT(*) AS V FROM (SELECT 1 X FROM DUAL) A, (SELECT 1 Y FROM DUAL) B WHERE A.X = B.Y(+);

-- [CHANGE-PROBE-44] 环境信息：连接到的达梦版本
SELECT 'ENV-VERSION' AS PROBE_ID, BANNER AS V FROM V$VERSION WHERE ROWNUM = 1;

-- [CHANGE-PROBE-45] 负向对照：不存在的函数，本条必须失败
SELECT 'NEG-NO-SUCH-FUNCTION' AS PROBE_ID, NO_SUCH_FUNCTION_DM8(1) AS V FROM DUAL;

-- [CHANGE-PROBE-46] 负向对照：不存在的表，本条必须失败
SELECT 'NEG-NO-SUCH-TABLE' AS PROBE_ID, X AS V FROM NO_SUCH_TABLE_ZZZ;
